# Generated by Django 5.1.4 on 2025-01-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
