# Generated by Django 5.1.4 on 2025-01-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts/'),
        ),
    ]
